[package]
name = "openssh-sftp-protocol"
version = "0.7.0"
edition = "2021"

license = "MIT"
description = "Data format used to communicate with openssh mux server."
repository = "https://github.com/NobodyXu/openssh-sftp-client"

keywords = ["ssh", "multiplex", "async", "network", "sftp"]
categories = ["asynchronous", "network-programming", "api-bindings"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ssh_format = "0.7.0"

bitflags = "1.3.2"
vec-strings = { version = "0.3.0", features = ["serde"] }

[dev-dependencies]
serde_json = "1.0"
serde_test = "1.0"
once_cell = "1.8.0"
